GET http://localhost:3030/api/user/get-user HTTP/1.1

###
GET http://localhost:3030/api/user/1 HTTP/1.1

###
POST http://localhost:3030/api/user/add-user HTTP/1.1
content-type: application/json
{
    "user_name": "khamlar",
    "password":"aaabbccddd",
    "staff_id":1
}

###
DELETE http://localhost:3030/api/user/2 HTTP/1.1

###

PUT http://localhost:3030/api/user/edit-user HTTP/1.1
Content-Type: : application/json
{
    "id": 3,
    "user_name": "khamlar",
    "password":"aaabbccddd",
    "staff_id":1
}